"""
LEGACYX — Decision Contract Engine (Feature 2).

Manages language-agnostic Decision Contracts extracted from Business Rule DNA.
Contracts define expected business decisions independent of Java or modern syntax.
"""

from typing import Any, Optional
import uuid
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

from app.models.business_rule import BusinessRule
from app.models.decision_contract import ContractStatus, DecisionContract


class DecisionContractEngine:
    """
    Engine for creating, extracting, and validating Decision Contracts.
    """

    async def generate_contracts_from_rules(
        self,
        analysis_id: str,
        repository_id: str,
        db: AsyncSession,
    ) -> list[DecisionContract]:
        """
        Extracts formal decision contracts from discovered BusinessRule records in an analysis run.
        """
        # Check existing contracts to avoid duplicates
        existing_stmt = select(DecisionContract).where(DecisionContract.analysis_id == analysis_id)
        existing_res = await db.execute(existing_stmt)
        existing_contracts = existing_res.scalars().all()
        if existing_contracts:
            return list(existing_contracts)

        # Fetch business rules
        rules_stmt = select(BusinessRule).where(BusinessRule.analysis_id == analysis_id)
        rules_res = await db.execute(rules_stmt)
        rules = rules_res.scalars().all()

        created_contracts: list[DecisionContract] = []
        counter = 100

        for rule in rules:
            counter += 1
            domain = "FINANCIAL_SERVICES"
            if "fraud" in rule.relative_file_path.lower() or "risk" in rule.title.lower():
                domain = "FRAUD_DETECTION"
                contract_code = f"FRAUD-RISK-{counter}"
            elif "account" in rule.relative_file_path.lower():
                domain = "ACCOUNT_PROCESSING"
                contract_code = f"ACCT-POLICY-{counter}"
            elif "transfer" in rule.relative_file_path.lower() or "trans" in rule.title.lower():
                domain = "TRANSACTION_APPROVAL"
                contract_code = f"TX-APPROVAL-{counter}"
            else:
                contract_code = f"BIZ-CONTRACT-{counter}"

            # Format conditions
            conditions = []
            if rule.condition_expression:
                conditions.append(rule.condition_expression)
            elif rule.calculation_formula:
                conditions.append(f"CALCULATION: {rule.calculation_formula}")
            else:
                conditions.append("DEFAULT_RULE_PRECONDITION")

            # Determine expected decision
            if rule.threshold_value:
                expected_decision = "REQUIRE_APPROVAL" if ">" in (rule.threshold_operator or ">") else "ALLOW"
            elif rule.rule_type == "VALIDATION":
                expected_decision = "HALT_ON_INVALID"
            elif rule.rule_type == "CALCULATION":
                expected_decision = "APPLY_DERIVATION"
            elif rule.new_state:
                expected_decision = f"TRANSITION_{rule.new_state}"
            else:
                expected_decision = "PROCESS"

            inputs = rule.inputs if rule.inputs else [
                {"name": "transactionAmount", "type": "BigDecimal", "sample_value": 50000.0},
                {"name": "accountStatus", "type": "String", "sample_value": "ACTIVE"},
            ]

            expected_outputs = {
                "decision": expected_decision,
                "rule_type": str(rule.rule_type),
                "threshold": rule.threshold_value,
                "resulting_state": rule.new_state or "PROCESSED",
            }

            evidence = {
                "source_file": rule.relative_file_path,
                "line_start": rule.line_start,
                "line_end": rule.line_end,
                "construct": rule.source_construct,
                "extraction_reason": rule.extraction_reason,
            }

            contract = DecisionContract(
                contract_id=contract_code,
                name=f"Contract: {rule.title}",
                business_domain=domain,
                repository_id=repository_id,
                analysis_id=analysis_id,
                business_rule_id=rule.id,
                inputs=inputs,
                conditions=conditions,
                expected_decision=expected_decision,
                expected_outputs=expected_outputs,
                version=1,
                status=ContractStatus.ACTIVE,
                is_critical=rule.is_critical,
                evidence=evidence,
                notes=rule.business_meaning or "Autogenerated contract grounded in Java AST evidence",
            )
            db.add(contract)
            created_contracts.append(contract)

        await db.commit()
        return created_contracts

    async def list_contracts(
        self,
        repository_id: str,
        domain: Optional[str],
        db: AsyncSession,
    ) -> list[DecisionContract]:
        stmt = select(DecisionContract).where(DecisionContract.repository_id == repository_id)
        if domain:
            stmt = stmt.where(DecisionContract.business_domain == domain)
        stmt = stmt.order_by(DecisionContract.contract_id.asc())
        res = await db.execute(stmt)
        return list(res.scalars().all())

    async def get_contract(
        self,
        contract_id: str,
        db: AsyncSession,
    ) -> Optional[DecisionContract]:
        stmt = select(DecisionContract).where(
            (DecisionContract.id == contract_id) | (DecisionContract.contract_id == contract_id)
        )
        res = await db.execute(stmt)
        return res.scalar_one_or_none()


contract_engine = DecisionContractEngine()
